os:
  - linux
dist: bionic
language: scala
jdk:
  - openjdk8
python:
  - 3.7

before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U wheel
  - sudo pip3 install -U virtualenvwrapper
  - python3 -m pip install pipenv
  - (cd python;pipenv install --dev)
  - mvn -q clean install -DskipTests
  - find core/target/ -iregex "python-adapter\/target\/sedona-python-adapter-[0-9]\.[0-9]\.[0-9]-incubator\(-SNAPSHOT\)?\.jar" -exec cp {} $SPARK_HOME/jars \;
  - (cd python;pipenv run pytest tests)

script:
  - (cd python;pipenv install --dev)