# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Continuous integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - run: git submodule update --init --recursive # Checkout Git submodule if necessary
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - uses: actions/setup-java@v1
      with:
        java-version: '8'
    - run: mvn -q clean install
    - uses: vemonet/setup-spark@v1
      with:
        spark-version: '3.0.1' # Exact version
    - run: export PYTHONPATH=$SPARK_HOME/python
    - run: sudo apt-get -y install python3-pip python-dev
    - run: sudo pip3 install -U setuptools
    - run: sudo pip3 install -U wheel
    - run: sudo pip3 install -U virtualenvwrapper
    - run: python3 -m pip install pipenv
    - run: (cd python;pipenv install --dev)
    - run: find python-adapter/target/ -iregex "python-adapter\/target\/sedona-python-adapter-[0-9]\.[0-9]\.[0-9]-incubator\(-SNAPSHOT\)?\.jar" -exec cp {} $SPARK_HOME/jars \;
    - run: (cd python;pipenv run pytest tests)
